#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

export AWS_DEFAULT_REGION=eu-west-2
export AWS_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/prm-deductions-automatic-trigger-e2e
export NHS_SERVICE=prm-deductions-automatic-trigger-e2e
AWS_HELPERS_VERSION=0.2.10
echo "AWS helper scripts version: $AWS_HELPERS_VERSION"

# Do not change the file name as the aws helper scripts depend on it
AWS_HELPERS_FILE="utils/$AWS_HELPERS_VERSION/aws-helpers"

mkdir -p "utils/$AWS_HELPERS_VERSION"
if [[ ! -f $AWS_HELPERS_FILE ]];then
  wget --quiet -O $AWS_HELPERS_FILE https://github.com/nhsconnect/prm-deductions-support-infra/releases/download/${AWS_HELPERS_VERSION}/aws-helpers
fi
chmod +x $AWS_HELPERS_FILE
source $AWS_HELPERS_FILE

####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function set_image_tag() {
  export IMAGE_TAG=$(git rev-parse HEAD | cut -c 1-8)
}

function get_aws_account_id {
    export AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
}

function configure_local_envs {
  export LOG_LEVEL=debug
  export NHS_ENVIRONMENT=local
}

function configure_mesh_access {
  mesh_mailbox_id="/repo/dev/user-input/external/mesh-mailbox-id"
  echo "${mesh_mailbox_id}"
  mesh_client_cert="/repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-cert"
  echo "${mesh_client_cert}"
  mesh_client_key="/repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-key"

  export MESH_MAILBOX_ID=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${mesh_mailbox_id} | jq -r .Parameter.Value")
  export MESH_CLIENT_CERT=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${mesh_client_cert} | jq -r .Parameter.Value")
  export MESH_CLIENT_KEY=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${mesh_client_key} | jq -r .Parameter.Value")
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  _build)
      rm -rf build/
      gradle assemble
      ;;
  build)
      dojo "./tasks _build"
      ;;
  _dep)
      gradle dependencyCheckAnalyze
      ;;
  dep)
      dojo "./tasks _dep"
      ;;
  _test_e2e)
      gradle test
      ;;
  test_e2e)
      check_env
      assume_environment_role $NHS_ENVIRONMENT
      get_aws_account_id
      dojo "./tasks _test_e2e"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
