#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

export AWS_DEFAULT_REGION=eu-west-2
export AWS_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/prm-deductions-automatic-trigger-e2e
export NHS_SERVICE=prm-deductions-automatic-trigger-e2e
AWS_HELPERS_VERSION=0.2.19
echo "AWS helper scripts version: $AWS_HELPERS_VERSION"

# Do not change the file name as the aws helper scripts depend on it
AWS_HELPERS_FILE="utils/$AWS_HELPERS_VERSION/aws-helpers"

mkdir -p "utils/$AWS_HELPERS_VERSION"
if [[ ! -f $AWS_HELPERS_FILE ]];then
  wget --quiet -O $AWS_HELPERS_FILE https://github.com/nhsconnect/prm-deductions-support-infra/releases/download/${AWS_HELPERS_VERSION}/aws-helpers
fi
chmod +x $AWS_HELPERS_FILE
source $AWS_HELPERS_FILE

####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function set_image_tag() {
  export IMAGE_TAG=$(git rev-parse HEAD | cut -c 1-8)
}

function configure_local_envs {
  export LOG_LEVEL=debug
  export NHS_ENVIRONMENT=local
}

function configure_mesh_access {
  mesh_mailbox_id="/repo/dev/user-input/external/mesh-mailbox-id"
  echo "${mesh_mailbox_id}"
  mesh_client_cert="/repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-cert"
  echo "${mesh_client_cert}"
  mesh_client_key="/repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-key"

  export MESH_MAILBOX_ID=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${mesh_mailbox_id} | jq -r .Parameter.Value")
  export MESH_CLIENT_CERT=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${mesh_client_cert} | jq -r .Parameter.Value")
  export MESH_CLIENT_KEY=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${mesh_client_key} | jq -r .Parameter.Value")
}

function get_suspension_service_cluster_name {
  cluster_ssm_param_name="/repo/${NHS_ENVIRONMENT}/output/suspension-service/suspension-service-ecs-cluster-name"
  export SUSPENSION_SERVICE_CLUSTER_NAME=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${cluster_ssm_param_name} | jq -r .Parameter.Value")
  echo $SUSPENSION_SERVICE_CLUSTER_NAME
}

function get_running_task_count {
  echo $(aws ecs describe-clusters \
        --cluster "$1" \
        --region "$AWS_REGION" \
        | jq -r '.clusters[0].runningTasksCount')
}

function check_suspension_service {
  if [[ "$NHS_ENVIRONMENT" != "test" ]]; then
    echo "We're not checking suspension-service for dev env"
    return 0
  fi
  POLLING_ATTEMPTS_LEFT=6
  CLUSTER_NAME=$(get_suspension_service_cluster_name)
  while [ "$POLLING_ATTEMPTS_LEFT" -gt "0" ]; do
    TASKS_COUNT=$(get_running_task_count ${CLUSTER_NAME})

    echo "Number of running tasks found: $TASKS_COUNT"

    if [[ "$TASKS_COUNT" -eq "0" || "$TASKS_COUNT" == "null" ]]; then
      let POLLING_ATTEMPTS_LEFT--
      echo "No running task found. Making another attempt. Attempts left: $POLLING_ATTEMPTS_LEFT"
      sleep 180 #3 mins
    else
      echo "Found $TASKS_COUNT running tasks in $CLUSTER_NAME"
      return 0
    fi
  done

  echo "Can't find a running task in $CLUSTER_NAME"
  exit 1
}

function set_required_role_arn_from_assumed_role() {
  export REQUIRED_ROLE_ARN=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Arn")
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  _dep)
      gradle dependencyCheckAnalyze
      ;;
  dep)
      dojo "./tasks _dep"
      ;;
  _test_e2e)
      gradle test --tests *EndToEndTest
      ;;
  test_e2e)
      check_env
      assume_environment_role $NHS_ENVIRONMENT
      check_suspension_service
      dojo "./tasks _test_e2e"
      ;;
  _test_performance)
      gradle test --tests *PerformanceTest
      ;;
  test_performance_local) # using local user auth
      check_env
      assume_environment_role $NHS_ENVIRONMENT
      dojo "./tasks _test_performance"
      ;;
  test_performance) # in pipeline
      check_env

      assume_environment_role $NHS_ENVIRONMENT
      set_required_role_arn_from_assumed_role
      echo "set REQUIRED_ROLE_ARN to $REQUIRED_ROLE_ARN for long-running test process"

      echo "NB: clearing temporary auth session credentials to allow native AWS auth access to re-assume role after expiry"
      _clear_aws_env_credentials

      dojo "./tasks _test_performance"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
