package uk.nhs.prm.e2etests.enumeration;

public enum ConversationTransferStatus {
    INBOUND_STARTED,
    INBOUND_REQUEST_SENT,
    INBOUND_CONTINUE_REQUEST_SENT,
    INBOUND_FAILED,
    INBOUND_TIMEOUT,
    INBOUND_COMPLETE,
    OUTBOUND_STARTED,
    OUTBOUND_SENT_CORE,
    OUTBOUND_CONTINUE_REQUEST_RECEIVED,
    OUTBOUND_SENT_FRAGMENTS,
    OUTBOUND_COMPLETE,
    OUTBOUND_FAILED
}
