package uk.nhs.prm.e2etests.configuration;

import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Bean;
import lombok.AllArgsConstructor;

import static software.amazon.awssdk.regions.Region.EU_WEST_2;

@Configuration
@AllArgsConstructor(onConstructor = @__(@Autowired))
public class DatabaseConfiguration {
    private final AwsCredentialsProvider awsCredentialsProvider;

    @Bean
    public DynamoDbEnhancedClient dynamoDbEnhancedClient() {
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(DynamoDbClient.builder()
                    .region(EU_WEST_2)
                    .credentialsProvider(awsCredentialsProvider).build())
                .extensions(AutoGeneratedTimestampRecordExtension.create())
                .build();
    }
}