package uk.nhs.prm.e2etests.model.database;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.OffsetDateTimeAsStringAttributeConverter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

import java.time.OffsetDateTime;

@Setter
@Builder
@DynamoDbBean
@NoArgsConstructor
@AllArgsConstructor
public class ConversationRecord {
    private String inboundConversationId; // Partition Key
    private String layer; // Sort Key
    private String outboundConversationId;
    private String nhsNumber;
    private String transferStatus;
    private String failureCode;
    private String failureReason;
    private String sourceGp;
    private String destinationGp;
    private String nemsMessageId;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private Integer deletedAt;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("InboundConversationId")
    public String getInboundConversationId() {
        return inboundConversationId.toLowerCase();
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("Layer")
    public String getLayer() {
        return layer;
    }

    @DynamoDbAttribute("OutboundConversationId")
    @DynamoDbSecondaryPartitionKey(indexNames = "OutboundConversationIdSecondaryIndex")
    public String getOutboundConversationId() {
        return outboundConversationId;
    }

    @DynamoDbAttribute("NhsNumber")
    @DynamoDbSecondaryPartitionKey(indexNames = "NhsNumberSecondaryIndex")
    public String getNhsNumber() {
        return nhsNumber;
    }

    @DynamoDbAttribute("TransferStatus")
    public String getTransferStatus() {
        return transferStatus;
    }

    @DynamoDbAttribute("FailureCode")
    public String getFailureCode() {
        return failureCode;
    }

    @DynamoDbAttribute("FailureReason")
    public String getFailureReason() {
        return failureReason;
    }

    @DynamoDbAttribute("SourceGp")
    public String getSourceGp() {
        return sourceGp;
    }

    @DynamoDbAttribute("DestinationGp")
    public String getDestinationGp() {
        return destinationGp;
    }

    @DynamoDbAttribute("NemsMessageId")
    public String getNemsMessageId() {
        return nemsMessageId;
    }

    @DynamoDbAttribute("CreatedAt")
    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @DynamoDbConvertedBy(OffsetDateTimeAsStringAttributeConverter.class)
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @DynamoDbAttribute("UpdatedAt")
    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbConvertedBy(OffsetDateTimeAsStringAttributeConverter.class)
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @DynamoDbAttribute("DeletedAt")
    public Integer getDeletedAt() {
        return deletedAt;
    }
}