package uk.nhs.prm.e2etests.model.database;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.OffsetDateTimeAsStringAttributeConverter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

import java.time.Instant;

import static uk.nhs.prm.e2etests.utility.DateTimeUtility.getIsoTimestampForString;

@Getter
@Builder
@DynamoDbBean
@NoArgsConstructor
@AllArgsConstructor
public class ConversationRecord {
    private String inboundConversationId; // Partition Key
    private String layer; // Sort Key
    private String outboundConversationId;
    private String nhsNumber;
    private String transferStatus;
    private String failureCode;
    private String failureReason;
    private String sourceGp;
    private String destinationGp;
    private String nemsMessageId;
    private String createdAt;
    private String updatedAt;
    private Integer deletedAt;
    private String AssociatedTest;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("InboundConversationId")
    public void setInboundConversationId(String inboundConversationId) {
        this.inboundConversationId = inboundConversationId;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("Layer")
    public void setLayer(String layer) {
        this.layer = layer;
    }

    @DynamoDbAttribute("OutboundConversationId")
    @DynamoDbSecondaryPartitionKey(indexNames = "OutboundConversationIdSecondaryIndex")
    public void setOutboundConversationId(String outboundConversationId) {
        this.outboundConversationId = outboundConversationId;
    }

    @DynamoDbAttribute("NhsNumber")
    @DynamoDbSecondaryPartitionKey(indexNames = "NhsNumberSecondaryIndex")
    public void setNhsNumber(String nhsNumber) {
        this.nhsNumber = nhsNumber;
    }

    @DynamoDbAttribute("TransferStatus")
    public void setTransferStatus(String transferStatus) {
        this.transferStatus = transferStatus;
    }

    @DynamoDbAttribute("FailureCode")
    public void setFailureCode(String failureCode) {
        this.failureCode = failureCode;
    }

    @DynamoDbAttribute("FailureReason")
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    @DynamoDbAttribute("SourceGp")
    public void setSourceGp(String sourceGp) {
        this.sourceGp = sourceGp;
    }

    @DynamoDbAttribute("DestinationGp")
    public void setDestinationGp(String destinationGp) {
        this.destinationGp = destinationGp;
    }

    @DynamoDbAttribute("NemsMessageId")
    public void setNemsMessageId(String nemsMessageId) {
        this.nemsMessageId = nemsMessageId;
    }

    @DynamoDbAttribute("CreatedAt")
    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @DynamoDbConvertedBy(OffsetDateTimeAsStringAttributeConverter.class)
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = getIsoTimestampForString(createdAt);
    }

    @DynamoDbAttribute("UpdatedAt")
    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbConvertedBy(OffsetDateTimeAsStringAttributeConverter.class)
    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = getIsoTimestampForString(updatedAt);
    }

    @DynamoDbAttribute("DeletedAt")
    public void setDeletedAt(Integer deletedAt) {
        this.deletedAt = deletedAt;
    }

    @DynamoDbAttribute("AssociatedTest")
    public void setAssociatedTest(String associatedTest) {
        this.AssociatedTest = associatedTest;
    }
}