/*
 * This file is generated by jOOQ.
 */
package uk.nhs.prm.deduction.e2e.ehroutdb;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import uk.nhs.prm.deduction.e2e.ehroutdb.tables.Acknowledgements;
import uk.nhs.prm.deduction.e2e.ehroutdb.tables.records.AcknowledgementsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AcknowledgementsRecord> ACKNOWLEDGEMENTS_PKEY = UniqueKeys0.ACKNOWLEDGEMENTS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AcknowledgementsRecord> ACKNOWLEDGEMENTS_PKEY = Internal.createUniqueKey(Acknowledgements.ACKNOWLEDGEMENTS, "acknowledgements_pkey", new TableField[] { Acknowledgements.ACKNOWLEDGEMENTS.MESSAGE_ID }, true);
    }
}
