/*
 * This file is generated by jOOQ.
 */
package uk.nhs.prm.deduction.e2e.ehroutdb;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import uk.nhs.prm.deduction.e2e.ehroutdb.tables.Acknowledgements;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1436157980;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.acknowledgements</code>.
     */
    public final Acknowledgements ACKNOWLEDGEMENTS = Acknowledgements.ACKNOWLEDGEMENTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Acknowledgements.ACKNOWLEDGEMENTS);
    }
}
