/*
 * This file is generated by jOOQ.
 */
package uk.nhs.prm.deduction.e2e.ehroutdb;


import uk.nhs.prm.deduction.e2e.ehroutdb.tables.Acknowledgements;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.acknowledgements</code>.
     */
    public static final Acknowledgements ACKNOWLEDGEMENTS = Acknowledgements.ACKNOWLEDGEMENTS;
}
