/*
 * This file is generated by jOOQ.
 */
package uk.nhs.prm.deduction.e2e.ehroutdb.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import uk.nhs.prm.deduction.e2e.ehroutdb.tables.Acknowledgements;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AcknowledgementsRecord extends UpdatableRecordImpl<AcknowledgementsRecord> implements Record9<UUID, String, String, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 2054103351;

    /**
     * Setter for <code>public.acknowledgements.message_id</code>.
     */
    public void setMessageId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acknowledgements.message_id</code>.
     */
    public UUID getMessageId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.acknowledgements.acknowledgement_type_code</code>.
     */
    public void setAcknowledgementTypeCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acknowledgements.acknowledgement_type_code</code>.
     */
    public String getAcknowledgementTypeCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.acknowledgements.acknowledgement_detail</code>.
     */
    public void setAcknowledgementDetail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.acknowledgements.acknowledgement_detail</code>.
     */
    public String getAcknowledgementDetail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.acknowledgements.service</code>.
     */
    public void setService(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.acknowledgements.service</code>.
     */
    public String getService() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.acknowledgements.referenced_message_id</code>.
     */
    public void setReferencedMessageId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.acknowledgements.referenced_message_id</code>.
     */
    public String getReferencedMessageId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.acknowledgements.message_ref</code>.
     */
    public void setMessageRef(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.acknowledgements.message_ref</code>.
     */
    public String getMessageRef() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.acknowledgements.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.acknowledgements.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.acknowledgements.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.acknowledgements.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.acknowledgements.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.acknowledgements.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, String, String, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, String, String, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Acknowledgements.ACKNOWLEDGEMENTS.MESSAGE_ID;
    }

    @Override
    public Field<String> field2() {
        return Acknowledgements.ACKNOWLEDGEMENTS.ACKNOWLEDGEMENT_TYPE_CODE;
    }

    @Override
    public Field<String> field3() {
        return Acknowledgements.ACKNOWLEDGEMENTS.ACKNOWLEDGEMENT_DETAIL;
    }

    @Override
    public Field<String> field4() {
        return Acknowledgements.ACKNOWLEDGEMENTS.SERVICE;
    }

    @Override
    public Field<String> field5() {
        return Acknowledgements.ACKNOWLEDGEMENTS.REFERENCED_MESSAGE_ID;
    }

    @Override
    public Field<String> field6() {
        return Acknowledgements.ACKNOWLEDGEMENTS.MESSAGE_REF;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Acknowledgements.ACKNOWLEDGEMENTS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return Acknowledgements.ACKNOWLEDGEMENTS.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return Acknowledgements.ACKNOWLEDGEMENTS.DELETED_AT;
    }

    @Override
    public UUID component1() {
        return getMessageId();
    }

    @Override
    public String component2() {
        return getAcknowledgementTypeCode();
    }

    @Override
    public String component3() {
        return getAcknowledgementDetail();
    }

    @Override
    public String component4() {
        return getService();
    }

    @Override
    public String component5() {
        return getReferencedMessageId();
    }

    @Override
    public String component6() {
        return getMessageRef();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component9() {
        return getDeletedAt();
    }

    @Override
    public UUID value1() {
        return getMessageId();
    }

    @Override
    public String value2() {
        return getAcknowledgementTypeCode();
    }

    @Override
    public String value3() {
        return getAcknowledgementDetail();
    }

    @Override
    public String value4() {
        return getService();
    }

    @Override
    public String value5() {
        return getReferencedMessageId();
    }

    @Override
    public String value6() {
        return getMessageRef();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value9() {
        return getDeletedAt();
    }

    @Override
    public AcknowledgementsRecord value1(UUID value) {
        setMessageId(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value2(String value) {
        setAcknowledgementTypeCode(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value3(String value) {
        setAcknowledgementDetail(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value4(String value) {
        setService(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value5(String value) {
        setReferencedMessageId(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value6(String value) {
        setMessageRef(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value7(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value8(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord value9(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public AcknowledgementsRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6, OffsetDateTime value7, OffsetDateTime value8, OffsetDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AcknowledgementsRecord
     */
    public AcknowledgementsRecord() {
        super(Acknowledgements.ACKNOWLEDGEMENTS);
    }

    /**
     * Create a detached, initialised AcknowledgementsRecord
     */
    public AcknowledgementsRecord(UUID messageId, String acknowledgementTypeCode, String acknowledgementDetail, String service, String referencedMessageId, String messageRef, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(Acknowledgements.ACKNOWLEDGEMENTS);

        set(0, messageId);
        set(1, acknowledgementTypeCode);
        set(2, acknowledgementDetail);
        set(3, service);
        set(4, referencedMessageId);
        set(5, messageRef);
        set(6, createdAt);
        set(7, updatedAt);
        set(8, deletedAt);
    }
}
